name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # veya hangi branch’ten deploy istiyorsan onu yaz

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project (disable CI=true to avoid warning-as-error)
      run: |
        CI='' npm run build

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # GitHub otomatik verir
        action: "upload"
        app_location: "/"              # Projenin kök dizini
        output_location: "build"       # React için "build"
